Feature/api endpoint
curiosum-dev/kanta pull request #36
Opened 2023-10-11 05:03 UTC by arturz

2023-10-11 07:14 UTC, ravensiris requested changes

2023-10-11 07:14 UTC, ravensiris commented on lib/kanta/query.ex
> +              page_size: per_page || @default_page_size,
Might not be sufficient to use `|| default` here.
Since this is an external API I'd add `when is_integer(page) and is_integer(per_page)`.
And then instead of `|| default` I'd use `max(page, 1)` and `max(per_page, @minimum_per_page)`.
And lastly change: `def paginate(query, nil, nil), do: paginate(query, 1, @default_page_size)` to: `def paginate(query, _, _), do: paginate(query, 1, @default_page_size)` and put it at the end.
This way weird things don't happen when someone writes a bad client, defaulting to first page on invalid requests and disallowing invalid indexes such as `-1`

2023-10-11 07:14 UTC, ravensiris commented on lib/kanta/translations/context.ex
> +  @required_fields ~w(name)a
I'd use:
```elixir
@required_fields ~w(name)a
@optional_fields ~w(description color)a

# ...

cast(@optional_fields ++ @required_fields)
```
This way you don't have to repeat required fields

2023-10-11 07:14 UTC, ravensiris commented on lib/kanta/translations/domain.ex
> +  @required_fields ~w(name)a
Same here I'd split this to required and optional fields

2023-10-11 07:14 UTC, ravensiris commented on lib/kanta/translations/locale.ex
> +  @derive {Jason.Encoder, only: [:id] ++ @all_fields}
Might be better to use one of those

To encode all fields:
```elixir
@derive Jason.Encoder
```
To encode all except:
```elixir
@derive {Jason.Encoder, except: [...]}
```

2023-10-11 07:14 UTC, ravensiris commented on lib/kanta/translations/messages/finders/list_messages.ex
> +    |> filter_query(Map.take(params[:filter] || %{}, @available_filters))
I'd put:
```elixir
filters = params[:filter] || %{}
query_filters = Map.take(filters, @available_filters)
```

since filters is used multiple times and `Map.take` is nested

2023-10-11 07:14 UTC, ravensiris commented on lib/kanta_web/plugs/api_auth_plug.ex
I think it's a bad idea to roll your own authentication, especially that you only have this simple key check(the sha256 is not providing any real security).
It would be better to let other developers integrating Kanta to wrap the routes with something like this:
https://hexdocs.pm/pow/api.html

Then you don't have to maintain your own authentication plugin that might raise security concerns.

2023-10-11 08:04 UTC, arturz commented on lib/kanta/translations/locale.ex
> +  @derive {Jason.Encoder, only: [:id] ++ @all_fields}
Regarding your first proposal, associacions are also serialized and I don't want that. Regarding the other one, it is simpler to just use `only: [:id] ++ fields` than listing all associacions to except.

2023-10-11 08:53 UTC, arturz commented on lib/kanta_web/plugs/api_auth_plug.ex
I agree that SHA256 is not providing any real security, but I don't see how Pow would increase it either. I analysed the code and come to conslusion that is suited for client-server authentication, not server-server. Could you provide some example?
I also think that real security improvement would come from using public-key cryptography. I don't know any Elixir library that handles this use case and implementing it on your own would be cumbersome, though it is definitely something that should be considered in the future.

2023-10-11 10:08 UTC, arturz commented on lib/kanta_web/plugs/api_auth_plug.ex
I will add a way to disable default authorization in case somebody wants to use their own.

2023-10-11 12:49 UTC, ravensiris commented on lib/kanta_web/plugs/api_auth_plug.ex
General idea is to hand off security concerns to libraries that are made for it.
But leaving a way for other devs to override this might be good enough.
I also don't see much of an attack vector except if the request is done through HTTP unencrypted it would be easy to capture and figure out the key.
The most important part missing here would be convenience things like having permissions per client, revoking keys, auto expiring keys(for keys with timestamp signatures).

2023-10-12 08:52 UTC, vi0dine reviewed
Apart from the overall absence of error handling and the lack of error code responses on the API side, I have no significant remarks to make.

2023-10-13 15:10 UTC, merged